include $(srctree)/drivers/misc/mediatek/Makefile.custom

# Linux driver folder
ccflags-y += -I$(srctree)/drivers/misc/mediatek/mach/$(MTK_PLATFORM)/$(ARCH_MTK_PROJECT)/touchpanel/mstar2238/
ccflags-y += -I$(srctree)/arch/arm/mach-$(MTK_PLATFORM)/$(ARCH_MTK_PROJECT)/touchpanel/mstar2238/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/mstar2238/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/

obj-y	+=  msg2238_driver.o


